# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 089b3071cbed58235b5b6db3d107ef05349c84acbd54e419d57c8178e8516fc2a3f1e2016f7dc1595477d74577a032ef4974da66c64ad1bec8cf08ae7b792b88

test:
  secret_key_base: 277332519765eb3e5be119bb11f8d974f3536fd08e1b030cab4765d5d066c6e5ffd77d81271ea96edba212c7e1e53481cac3968e1d27141d86c6bba9b29c0a9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
